POST http://localhost:{{port}}/tasks
Content-Type: application/json

{
  "text": "{{text}}"
}

> {% client.global.set('taskId', response.body.id); %}

###

POST http://localhost:{{port}}/tasks/{{taskId}}/tickoff
