### Login

POST http://localhost:{{port}}/users/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
  client.global.set("accessToken", response.body.accessToken);
  %}

### Note a new task

POST http://localhost:{{port}}/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "text": "{{text}}"
}

> {%
  client.global.set('taskId', response.body.id);
  %}

### Tick-off the created task

PUT http://localhost:{{port}}/tasks/{{taskId}}/tickoff
Authorization: Bearer {{accessToken}}
