### Register a new user

POST http://localhost:{{port}}/users
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

> {%
  client.test('Request executed successfully', function() {
    client.assert(response.status === 201, 'Response status is not 201')
  })
  %}
