POST http://localhost:3000/tasks
Content-Type: application/json

{ "text": "{{text}}" }

> {% client.global.set('taskId', response.body.id); %}

###

POST http://localhost:3000/tasks/{{taskId}}/archive

###

POST http://localhost:3000/tasks
Content-Type: application/json

{ "text": "{{text}}" }

> {% client.global.set('taskId', response.body.id); %}

###

POST http://localhost:3000/tasks/{{taskId}}/archive

###

GET http://localhost:3000/tasks/archived

###
